- name: Minecraft server
  hosts: all
  become: yes
  tasks:
  - name: copy and execute script
    script: scripts/startup.sh

  - name: Create systemd service unit for Minecraft
    copy:
      content: |
        [Unit]
        Description=Minecraft Server
        After=network.target

        [Service]
        User=root

        WorkingDirectory=/home/ec2-user/minecraft
        ExecStart=/usr/bin/java -jar /home/ec2-user/minecraft/server.jar nogui
        Restart=always
        RestartSec=3

        [Install]
        WantedBy=multi-user.target
      dest: /etc/systemd/system/minecraft.service
      mode: '0644'
      
  - name: Reload systemd to apply changes
    command: sudo systemctl daemon-reload

  - name: Enable minecraft.service
    command: sudo systemctl enable minecraft.service

  - name: Start minecraft.service
    command: sudo systemctl start minecraft.service
